# Generated by Django 5.0.6 on 2024-06-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employess',
        ),
        migrations.AlterModelTable(
            name='manager',
            table='managers',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='staff',
        ),
    ]
