# Generated by Django 5.0.6 on 2024-06-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management_system', '0002_alter_employee_table_alter_manager_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
        migrations.AlterModelTable(
            name='goal',
            table='goals',
        ),
        migrations.AlterModelTable(
            name='performancereview',
            table='performanceReviews',
        ),
        migrations.AlterModelTable(
            name='promotion',
            table='promotions',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='skills',
        ),
        migrations.AlterModelTable(
            name='training',
            table='trainings',
        ),
    ]
