# Generated by Django 5.0.6 on 2024-06-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management_system', '0004_staff_password'),
    ]
